# settings.py
FLUTTERWAVE_PUBLIC_KEY = 'FLWPUBK_TEST-XXXXXXXXXXXXXXXXXXXXXXXXX'
FLUTTERWAVE_SECRET_KEY = 'FLWSECK_TEST-XXXXXXXXXXXXXXXXXXXXXXXXX'
FLUTTERWAVE_ENCRYPTION_KEY = 'FLWSECK_TESTXXXXXXXXXXXXXXXXXXXXX'
CURRENCY = 'KES'  # Default currency for Kenya