# Generated by Django 5.1.5 on 2025-02-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_comments_count_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
